version: "3.9"

services:
  backend:
    image: utkarsh9246546/backend:latest
    ports:
      - "3000:8080" # Maps EC2 Port 3000 to Container Port 8080
    container_name: backend_container
    restart: always

  frontend:
    image: utkarsh9246546/frontend:latest
    ports:
      - "5000:5000" # Maps EC2 Port 5000 to Container Port 5000
    container_name: frontend_container
    depends_on:
      - backend
    restart: always